defaults:
    - _self_
    - task: emnist6
    - model: encoder

name: "${task.name} ${model.name} ${v}"
v: ???
seed: 57
device: cuda:0

num_workers: 6
pin_memory: true
batch_size: 256

optim: adam
lr: 3e-4
weight_decay: 0
warmup_epochs: -1
annealing_t0: -1
scheduler_patience: 20
num_epochs: 300

mixed_precision: false
use_tf32: true

disable_wandb: false
print_epochs: true
show_tqdm: false
save_best: true
save_directory: /home/agroskin/data/models
detect_anomalies: false

model_size: ???